// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC7Kwo9TTprYHigM8l_jF1UpK1BpkZJIo',
    appId: '1:673401807742:web:1475ec7995208c6d36492f',
    messagingSenderId: '673401807742',
    projectId: 'booki-d4bc8',
    authDomain: 'booki-d4bc8.firebaseapp.com',
    storageBucket: 'booki-d4bc8.appspot.com',
    measurementId: 'G-P63G36SXJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_mFeegPxhv2ScnsQyweIO5D3cb3k1TKA',
    appId: '1:673401807742:android:b4cacd0336c242d936492f',
    messagingSenderId: '673401807742',
    projectId: 'booki-d4bc8',
    storageBucket: 'booki-d4bc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKD-UWR_Jl56H2Uw36Ltkh46pPxe_TVho',
    appId: '1:673401807742:ios:a2e00aef749ddf3b36492f',
    messagingSenderId: '673401807742',
    projectId: 'booki-d4bc8',
    storageBucket: 'booki-d4bc8.appspot.com',
    iosClientId: '673401807742-me5h1u0fas7e0ti76p0585bilgnhq0nv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookiAdministrator',
  );
}
